# Generated by Django 3.2.5 on 2023-11-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_education', models.CharField(max_length=100)),
                ('personal_experience', models.TextField()),
                ('skill', models.TextField()),
                ('interest', models.TextField()),
                ('style', models.CharField(choices=[('1', '簡約'), ('2', '專業'), ('3', '創意')], max_length=10)),
                ('resume_file', models.FileField(upload_to='resume/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
